[package]
name = "mc-rend"
version = "0.1.0"
authors = ["MetaMuffin <metamuffin@yandex.com>"]
edition = "2018"


[dependencies]
image = "*"
byteorder = "*"
integer-encoding = "*"
imageproc = "*"
integer-sqrt = "*"
lazy_static = "*"
